### ISSUE TITLE
Dropping maintenance, takeovers welcome

### ISSUE THREAD

**Issue by andreasabel** [ulidtko/cabal-doctest#79]
Dear `cabal-doctest` users,
I am dropping my dependency on `cabal-doctest` and thus have no material interest in maintaining it.
So I am happy for a new maintainer to take over.
Express your interest in the comments below, maybe with a short motivating statement.

**Comment by ulidtko** [comment]
Hi @andreasabel, I did a cursory review of the package — on a background of having fiddled with `Cabal`-the-library, it does make *some* sense to me.

I'm also aware of its deprecation on hackage, and the general pain-point of doctests, as in haskell/cabal#2327. Although I don't yet see the entire doctesting landscape — I do write Haskell daily, and exploring it as-needed shouldn't be a big problem.

Am cautiously willing to rotate-in for maintainership.

AFAICS, the CI here doesn't do hackage uploads; I guess you'd want to add me to uploaders group, and at Maintain or Admin role in the github repo.

cc @phadej

**Comment by andreasabel** [comment]
@ulidtko Thanks, Maxim, for volunteering!  Great to have a new maintainer.

My work on this package was limited to keep it working with new releases of `Cabal` and `GHC`.  `Cabal-3.6` needed a release (1.0.9), from then, revisions on Hackage were sufficient. 

> I'm also aware of its deprecation on hackage

Maybe the deprecation was done in expectation of an integration of `doctest` support into `cabal`, but this never happened, so it could be un-deprecated.

The @haskellari organization is owned by @phadej, I cannot add new collaborators here myself.  Oleg is also co-maintainer on Hackage.  So he can give you the rights in this repo and the rights to upload and revise on Hackage.

@ulidtko : What is your hackage account?

@phadej, could you add Maxim here and on hackage?

**Comment by ulidtko** [comment]
> @ulidtko : What is your hackage account?

It's `ulidtko` there too

**Comment by phadej** [comment]
@ulidtko I'll be happy to transfer the repository out of `haskellari` organization.

**Comment by Bodigrim** [comment]
@andreasabel @phadej @ulidtko was there any conclusion about transfer of `cabal-doctest`?

**Comment by phadej** [comment]
All the discussion is in this issue...

**Comment by ulidtko** [comment]
@Bodigrim thanks for the ping.

@phadej you can now transfer to [ulidtko/doctest](https://github.com/ulidtko/cabal-doctest)

@andreasabel please add me to [maintainers](https://hackage.haskell.org/package/cabal-doctest/maintainers/)

**Comment by phadej** [comment]
@ulidtko "ulidtko/cabal-doctest already exists". I cannot transfer the repository to you because of that.

**Comment by ulidtko** [comment]
@phadej OK, removed. Please retry

**Comment by phadej** [comment]
@ulidtko GH complains, "You can only transfer a repository from an organization to yourself at this time". I added you as an admin to this repo, so you hopefully should be able to transfer it yourself.

**Comment by ulidtko** [comment]
@phadej Yes, that worked. :tada:  Neat

**Comment by andreasabel** [comment]
Sorry, was travelling for two weeks.  I added @ulidtko to the Hackage maintainers.
Thanks, Maxim, for taking over!
